# Задание к лекции "Функции"
Вам нужно помочь секретарю автоматизировать работу. Для этого нужно написать программу, которая будет на основе хранимых данных исполнять пользовательские команды.

Исходные данные имеют следующую структуру:

перечень всех документов
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]

перечень полок, на которых хранятся документы (если документ есть в documents, то он обязательно должен быть и в directories)
directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}

Общие требования к программе:

Код должен быть грамотно декомпозирован (каждая функция отвечает за свою конкретную задачу, дублирующийся функционал переиспользуется, а его код не повторяется);

в коде отсутствуют глобальные переменные (за исключением documents и directories);

пользовательский ввод обрабатывается в цикле while до тех пор, пока пользователь явно не завершит программу (вводом команды "q").

In [1]:
documents = [
 {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
 {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
 {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]



In [2]:
directories = {
 '1': ['2207 876234', '11-2'],
 '2': ['10006'],
 '3': []
}



# Operator

In [13]:
def input_user():
    while True:
        comand = input('Введите команду ')
        if comand == 'p':
            print(doc_owner(documents))
        elif comand == 's':
            print(doc_shelf(directories))
        elif comand == 'l':
            print(doc_info(documents, directories))
        elif comand == 'as':
            print(add_shelf(direct))
        elif comand == 'ds':
            print(del_doc(direct))
        elif comand == 'q':
            break
        else:
            print ('no')
    return

input_user()



Введите команду l
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
None
Введите команду q


# Задание 1
Пункт 1. Пользователь по команде "p" может узнать владельца документа по его номеру
Примеры работы:

Введите команду:
p

Введите номер документа:
10006

Результат:
Владелец документа: Аристарх Павлов

Введите команду:
p

Введите номер документа:
12345

Результат:
Документ не найден в базе

In [5]:
def doc_owner(names):
    num_doc = input('Введите номер документа ')
    for numbers in names:
        if num_doc == numbers['number']:
            return (f"Владелец документа: {numbers['name']}")
    return ('Документ не найден в базе')


doc_owner(documents)


Введите номер документа 10006


'Владелец документа: Аристарх Павлов'

# Пункт 2. Пользователь по команде "s" может по номеру документа узнать на какой полке он хранится
Примеры работы:

Введите команду:
s

Введите номер документа:
10006

Результат:
Документ хранится на полке: 2

Введите команду:
s

Введите номер документа:
12345

Результат:
Документ не найден в базе

In [6]:
def doc_shelf(shelfs):
    doc_num = input('Введите номер документа ')
    for key, number in shelfs.items():
        for numbers in number:
            if doc_num == (numbers):
                return (f'Документ хранится на полке: {key}')
    return ('Документ не найден в базе')

doc_shelf(directories)


Введите номер документа 10006


'Документ хранится на полке: 2'

# Пункт 3. Пользователь по команде "l" может увидеть полную информацию по всем документам
Пример работы:

Введите команду:
l

Результат:

№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

In [7]:
def doc_info(docs, dirs):
    for numbers in docs:
        doc_num = numbers['number']
        for key, values in dirs.items():
            if doc_num in values:
                print (f"№: {numbers['number']}, тип: {numbers['type']}, владелец: {numbers['name']}, полка хранения: {key}")


doc_info(documents, directories)

№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2


# Пункт 4. Пользователь по команде "ads" может добавить новую полку
Примеры работы:

Введите команду:
ads

Введите номер полки:
10

Результат:
Полка добавлена. Текущий перечень полок: 1, 2, 3, 10.

Введите команду:
ads

Введите номер полки:
1

Результат:
Такая полка уже существует. Текущий перечень полок: 1, 2, 3.

In [9]:
def add_shelf(shelf):
    sh_num = input('Введите номер полки ')
    if sh_num in list(directories):
        print ('no')
    else:
        directories[sh_num] = []

add_shelf(directories)


Введите номер полки 5


# Пункт 5. Пользователь по команде "ds" может удалить существующую полку из данных (только если она пустая)
Примеры работы:

Введите команду:
ds

Введите номер полки:
3

Результат:
Полка удалена. Текущий перечень полок: 1, 2.

Введите команду:
ds

Введите номер полки:
1

Результат:
На полке есть документа, удалите их перед удалением полки. Текущий перечень полок: 1, 2, 3.

Введите команду:
ds

Введите номер полки:
4

Результат:
Такой полки не существует. Текущий перечень полок: 1, 2, 3.

In [11]:
def del_doc(doc):
    input_shelf = input('Введите номер полки ')
    if input_shelf not in directories:
        print ('no shelf')
    elif input_shelf in directories and len(directories[input_shelf]) == 0:
        del(directories[input_shelf])
    else:
        print ('shelf have values')

del_doc(directories)

Введите номер полки 2
shelf have values
